add_syslinks("pthread", "gxiapi")
add_requires("opencv")
target("myrm")
    set_kind("binary")
    set_rules("mode.debug", "mode.release")
    set_optimize("fastest")
    add_includedirs("include")
    add_files("src/*.cpp")
    -- on_load(function (target)
    --     import("lib.detect.find_package")
    --     target:add(find_package("opencv"))
    --     end)
    add_packages("opencv")